### ISSUE TITLE
Support expires_at attribute

### ISSUE THREAD

**Issue by snakebyte91** [manhtukhang/vault-plugin-harbor#13]
It would be very good if it is possible to specify the lifetime (expires_at) of the robot token.

**Comment by manhtukhang** [comment]
Hi @snakebyte91,

You can specify this attribute with the role param `max_ttl`, e.g.:
```bash
$ vault write \
        harbor/roles/test-role \
        ttl=60s \
        max_ttl=8h \ 
        permissions=@role-permissions.json
```

In more detail, because Robot Account's duration (expires_at in the UI) is [counted in days](https://github.com/mittwald/goharbor-client/blob/ebbfe43da98cfc8b8e0bff7904cdb417436d0937/apiv2/model/robot_create.go#L27), so this time is computed by [rounding up from the `max_ttl`](https://github.com/manhtukhang/vault-plugin-harbor/blob/58806ed38ab3afd48260a32b674f3dcd123b6a16/path_creds.go#L129) (if `max_ttl < 1 day` then `duration = 1 day`, if `1 day <= max_ttl < 2 days` then `duration = 2 days`, and so on)

Hope this explanation can help!

**Comment by snakebyte91** [comment]
Hi @manhtukhang,

Thank you for the detailed explanation. It helped.

As I saw from the linked harbor API it would be a feature request to the harbor project to support tokens with a lifetime of an hour (for example).

**Comment by manhtukhang** [comment]
@snakebyte91,

IMO, the robot account lifetime isn't important because Vault always revokes (deletes) the token before it actually expires. For example, you can set `max_ttl` in the above role config to `60s`, then after `60 seconds`, Vault'll revoke the lease in internal storage and also **delete the created robot account on Harbor** despite its expire-time being `1 day`

**Comment by snakebyte91** [comment]
Perfect :) Thank you very much again.
